name: CI Pipeline

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Run Prisma Generate
        run: pnpm --filter server prisma:generate:ci

      - name: Perform Quality Checks
        run: pnpm quality

  build-and-push:
    needs: quality
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          docker build -t devleo/minerva:latest .
          docker push devleo/minerva:latest
